apiVersion: v1
kind: ConfigMap
metadata:
  name: kk-payments-config
  namespace: kijani-staging
data:
  DB_HOST: "staging-db.internal"
  ENVIRONMENT: "staging"
  LOG_LEVEL: "debug"
  RECEIPTS_BUCKET: "kijani-payments-receipts-staging"
