apiVersion: v1
kind: Service
metadata:
  name: kk-payments
  namespace: default
  labels:
    app: kk-payments
    environment: production
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: kk-payments
